server:
  port: 8280

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_db
    username: login
    password: password
  liquibase:
    liquibase-schema: liquibase
  security:
    user:
      password: password # password should be stored in password storage like Vault etc
      name: login
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true