server:
  port: 8280

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_db
    username: login
    password: password
  liquibase:
    liquibase-schema: liquibase
